### ISSUE TITLE
Consider adding “Spark with Java”

### ISSUE THREAD

**Issue by jgperrin** [onurakpolat/awesome-analytics#42]
Hello,

Please consider adding “Spark with Java” to your awesome list.

* [Spark with Java](https://www.manning.com/books/spark-with-java) - Apache Spark is a very powerful tool for analytics. This new book on Spark, in Manning's Early Access Program (MEAP), offers a very strong focus on Java, targeted towards software and data engineers. The author focuses on developing existing skills rather than learning Spark, Scala, and Hadoop at the same time. You can find the accompanying GitHub repositories [here](https://github.com/topics/sparkwithjava).

Thanks!

**Comment by koconder** [comment]
@jgperrin more of a stack or toolkit for analysis like R. Best submit in https://github.com/onurakpolat/awesome-bigdata if not in use
